// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdl9s2YzAPeMrvG9sa8Wx350FGK_IstkI',
    appId: '1:767522466287:web:a5552e31ca0aebd98a6e1a',
    messagingSenderId: '767522466287',
    projectId: 'fluttercrud-183cf',
    authDomain: 'fluttercrud-183cf.firebaseapp.com',
    storageBucket: 'fluttercrud-183cf.firebasestorage.app',
    measurementId: 'G-RM033VP1XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYVR1QBXXew6nnu6oOMI_iPFN0L7m7zxg',
    appId: '1:767522466287:android:dd855b6d15a1ba2b8a6e1a',
    messagingSenderId: '767522466287',
    projectId: 'fluttercrud-183cf',
    storageBucket: 'fluttercrud-183cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJtuW6z_3d1gQ_F7fCa4gHnU2wHyQ8IuU',
    appId: '1:767522466287:ios:1de743d9ae4e077a8a6e1a',
    messagingSenderId: '767522466287',
    projectId: 'fluttercrud-183cf',
    storageBucket: 'fluttercrud-183cf.firebasestorage.app',
    iosBundleId: 'com.example.flutterCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdl9s2YzAPeMrvG9sa8Wx350FGK_IstkI',
    appId: '1:767522466287:web:b23c0f5dd07e52a38a6e1a',
    messagingSenderId: '767522466287',
    projectId: 'fluttercrud-183cf',
    authDomain: 'fluttercrud-183cf.firebaseapp.com',
    storageBucket: 'fluttercrud-183cf.firebasestorage.app',
    measurementId: 'G-F7ZGZ0HVH1',
  );
}
